name: Test voicevox-client

on:
  push:
    branches:
      - main
      - rewrite
  pull_request:
    
jobs:
  tests:
    name: Test voicevox-client
    runs-on: ubuntu-latest
    services:
      voicevox:
        image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
        ports:
        - 50021:50021
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install depend
        run: python -m pip install -U .[tests]
      - name: Run test
        run: pytest
